### ISSUE TITLE
RegExp for semantic versions.

### ISSUE THREAD

**Issue by Paebbels** [pyTooling/pyTooling#12]
Might be added to pyTooling.Version.SemVersion, because it can be useful in that package as well. However, I don't think it's worth making Tip dependent on pyTooling.Version just for this line. This is in fact copied from https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string as-is. 

A possible enhancement to Tip is to build a container image in a separated workflow. Then, Tip itself would not need to install the dependencies at runtime; it would consume a ready-to-use ghcr.io/pyTooling/Tip container. In that context, having additional dependencies would be less harmful (not at all). Moreover, if we did that, we might add a proper CLI to Tip, through pyAttributes.

_Originally posted by @umarcor in https://github.com/pyTooling/Actions/pull/10#discussion_r761136851_

**Comment by umarcor** [comment]
FTR, `tip` was renamed to `releaser`, and it is now based on a container. See https://github.com/pyTooling/Actions/tree/main/releaser.
