### ISSUE TITLE
Circular dependency between pyTooling and pyTooling.Packaging

### ISSUE THREAD

**Issue by Xiretza** [pyTooling/pyTooling#20]
`pyTooling` can't be built without `pyTooling.Packaging` already installed:

```
Traceback (most recent call last):
  File "/build/python-pytooling/src/pyTooling-1.6.1/setup.py", line 35, in <module>
    from pyTooling.Packaging import DescribePythonPackageHostedOnGitHub
ModuleNotFoundError: No module named 'pyTooling.Packaging'
```

`pyTooling.Packaging` can't be built without `pyTooling` already installed:

```
ERROR: Could not import from 'pyTooling' !

Traceback (most recent call last):
  File "/build/python-pytooling-packaging/src/pyTooling.Packaging-0.5.0/setup.py", line 38, in <module>
    from Packaging  import DescribePythonPackageHostedOnGitHub
  File "/build/python-pytooling-packaging/src/pyTooling.Packaging-0.5.0/pyTooling/Packaging/__init__.py", line 255, in <module>
    DEFAULT_LICENSE =     Apache_2_0_License
NameError: name 'Apache_2_0_License' is not defined
```

This makes it impossible to create AUR packages for these projects.

**Comment by Paebbels** [comment]
@Xiretza I have merged `pyTooling.Packaging` into `pyTooling` itself. This is now v1.7.0.

I'll now update my other repositories and check if it's working as expected.
if you like you can try to package `pyTooling` standalone. It shouldn't need `pyTooling.Packaging` anymore.

There will be a v1.7.1 soon to collect missing changes that I might discover while testing it in other repositories.

**Comment by Paebbels** [comment]
@Xiretza I updated numerous repositories using pyTooling v1.7.0.
It looks good.

Please give it a try.

**Comment by Xiretza** [comment]
Sorry for the delay, it all seems to be working fine now - thanks for the quick fix!

**Comment by Paebbels** [comment]
No problem. 

The issue was on my side for making such a complex dependency :)
