### ISSUE TITLE
Generalise section 'Installation/Updates' of the documentation

### ISSUE THREAD

**Issue by umarcor** [pyTooling/pyTooling#23]
Instead of repeating the same info in the documentation of each project, we should generalise [pytooling.github.io/pyTooling/Installation](https://pytooling.github.io/pyTooling/Installation.html) and then use intersphinx to cross-reference it from the docs of other repos.

Since the section contains a subset of information related to standard Python solutions, we should add references to:

- The official docs of PIP.
- https://docs.python.org/3.9/installing/index.html#installing-index
- https://docs.python.org/3.11/install/index.html
- ...

Moreover, since pyTooling.Packaging is directly related to the mess of declaring dependencies (`requirements.txt`, `setup.py`, `pyproject.toml`), we should have some brief explanation (either here or in the section about Packaging). 

Ref: https://github.com/pyTooling/pyTooling.CLIAbstraction/pull/1#discussion_r774989933

**Comment by Paebbels** [comment]
I think an installation, update, removal instruction should be part of every repository's documentation also including the correct shell commands for copy paste.

We could extract some not so commonly used operations like installing from source or deleting a package to a common source, but I think installation and updating should be local to each repository.

As there should by a general pyTooling website / documentation, I think we don't need a special sub-website for `Installation`.

**Comment by umarcor** [comment]
The point is that there are ~20 repositories with the same info. That is a lot of maintenance work that I'm afraid no one will take care of, because it is of lowest priority for developers and users. Only users unexperienced with Python do need the current guidelines, and the codebases of EDAA and pyTooling are not targeting the most unexperienced users.

Most of the packages are unlikely to be installed or uninstalled explicitly (except by developers). The vast majority are not tools, but libraries. Therefore, most users will (should) handle them as dependencies, not copying commands into the terminal.

Furthermore, covering how to install, update and remove packages in Python is a huge task, because the packaging ecosystem is fragmented and caotic. We are currently explaining a very small subset, which does not comply with recommendations. Apart from explaining that multiple requirements files can exist per repo (some of which are not installed with the package), that they can coexist with a pyproject file, etc. mentioning venvs is compulsory.

I believe that gathering the references, explaining the common and not common operations in a generic way, explaining editor configuration details, etc. once would be enough effort already, provided that all the packages are handled in exactly the same way. These could be two monoliths only; the reason to split them into more repos is organizational. Having all repeated guidelines in a single place allows users to understand the very specific details about a package, if they exist.

Overall, I believe we should not rewrite what's already well written in the docs and tutorials of Python and pip. For instance: https://docs.python.org/3.9/installing/index.html#basic-usage.

> The standard packaging tools are all designed to be used from the command line.
>
> The following command will install the latest version of a module and its dependencies from the Python Package Index:
>
> `python -m pip install SomePackage`
> 
> It’s also possible to specify an exact or minimum version directly on the command line. When using comparator operators such as >, < or some other special character which get interpreted by shell, the package name and the version should be enclosed within double quotes:
> 
> `python -m pip install SomePackage==1.0.4`    # specific version
> `python -m pip install "SomePackage>=1.0.4"`  # minimum version
> 
> Normally, if a suitable module is already installed, attempting to install it again will have no effect. Upgrading existing modules must be requested explicitly:
> 
> `python -m pip install --upgrade SomePackage`

See also https://pip.pypa.io/en/stable/cli/pip_uninstall/.

Those two references are equivalent to the current installation guidelines, we can cross-reference through Sphinx, and we don't need to maintain them 20 times, because the Python community takes care of it.

**Comment by Paebbels** [comment]
pyTooling v5.0.0 got updated instructions for installations and updates.

**Comment by Paebbels** [comment]
pyTooling v6.0.0 will have an other enhancement of that section serving as a good blue print for such an instruction page.
