### ISSUE TITLE
Some packages seam to be missing for Clang32.

### ISSUE THREAD

**Issue by Paebbels** [pyTooling/pyTooling#41]
Some packages seam to be missing for Clang32.

_Originally posted by @Paebbels in https://github.com/pyTooling/pyTooling/pull/39#discussion_r819599324_

-------------
/cc @umarcor

**Comment by umarcor** [comment]
clang32 is not a first class environment in MSYS2. A lot of packages are missing.

**Comment by Paebbels** [comment]
So we don't need it in our tests, right?

I'll keep it in the Platform class in pyTooling, but no special care for it, right?

**Comment by Paebbels** [comment]
Clang32 will not be supported.
