### ISSUE TITLE
In Platform.py ARCH_x86_32 is used on the aarch64 architecture

### ISSUE THREAD

**Issue by yurivict** [pyTooling/pyTooling#83]
[This line](https://github.com/pyTooling/pyTooling/blob/main/pyTooling/Common/Platform.py#L155) appears to be wrong, because aarch64 is ARM and x86_32 is Intel architecture.

**Comment by Paebbels** [comment]
Yes, that's a bug.

**Comment by Paebbels** [comment]
This is addressed in #85.

**Comment by Paebbels** [comment]
It's merged. Release pipeline will push a package to PyPI in <1h.
